# Generated by Django 5.1.4 on 2025-01-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calorie_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyCalorieRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_calories', models.PositiveIntegerField(default=0)),
                ('food_items', models.ManyToManyField(to='my_app.food')),
            ],
        ),
    ]
